-- 외래 키 제약 조건을 가진 테이블 먼저 삭제 (의존성 역순)
DROP TABLE IF EXISTS SHARE;
DROP TABLE IF EXISTS BOOKMARK;
DROP TABLE IF EXISTS USER_LIKE_THREAD;
DROP TABLE IF EXISTS USER_LIKE_COMMENT;
DROP TABLE IF EXISTS COMMENT;
DROP TABLE IF EXISTS THREAD_TAG;
DROP TABLE IF EXISTS USER_INTEREST;
DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS THREAD;
DROP TABLE IF EXISTS REPOSITORY;
DROP TABLE IF EXISTS USER;
DROP TABLE IF EXISTS DEVELOPER;
