spring:
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: io.gittul.gittulbe.config.UpperSnakeCaseNamingStrategy
    properties:
      hibernate:
        show_sql: true
        format_sql: true
