spring:
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: io.gittul.config.hibernate.UpperSnakeCaseNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000
        show_sql: false
        format_sql: true
        highlight: true
