spring:
  profiles:
    default: dev
  config:
    import: application-secret.yml
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: io.gittul.core.config.hibernate.UpperSnakeCaseNamingStrategy
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Seoul
        default_batch_fetch_size: 1000

springdoc:
  api-docs:
    path: /docs/api
  swagger-ui:
    path: /docs/ui

logging:
  level:
    org:
      apache:
        coyote:
          http11:
            Http11Processor: WARN
